name: 'rust build info'
description: 'Get latest build and manifest information for rust dedicated server'
inputs:
  app_id:
    description: 'app id'
    required: true
    default: "258550"

outputs:
  build_id:
    description: Latest build id for the public branch
  build_updated_time:
    description: 'Unix timestamp that the build was updated'
  common_manifest_id:
    description: 'Manifest ID of Rust Common'
  linux_manifest_id:
    description: 'Manifest ID of Rust Linux'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app_id }}