name: Build Container
on: [ push ]

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the container
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Rust
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/whype-net/rust-depot-action:latest